### PR TITLE
fix | Trainer Condition

### PR DESCRIPTION
**Pull request by JanoChacon**
I used the public property of the BattleController, since the getOwner of the pixelEntity doesn't work :(

### CODE REVIEW

**Comment by StrangeOne101** [comment]
Hadn't managed to get to this yet. What was the reason for the closure?

**Comment by JanoChacon** [comment]
It was causing issues with multiplayer, the bt is coming as null :(

**Comment by StrangeOne101** [comment]
Yeah, multiplayer makes it much harder. A lot of the data isn't synced to the client at all, which is why some of the conditions don't work properly.

Appreciate the effort though! If you figure a solution, I'd love to know :)

**Comment by JanoChacon** [comment]
I was analyzing the classes, and an idea came to me. The rival Pokémon appears right at the trainer's coordinates. I'll try something with that, and if it works, I'll send a PR.

**Pull request closed without merging**
